# Generated by Django 4.2.11 on 2024-04-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regno', models.IntegerField(primary_key='regno', serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('cgpa', models.IntegerField()),
            ],
        ),
    ]
